{{- if .Values.aws  }}
{{- if eq .Values.aws.configMap.create true }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.aws.configMap.name }}
  labels:
    {{- include "launch.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
data:
  config: |-
    [profile {{ .Values.aws.profileName }}]
    role_arn = {{ index .Values.serviceAccount.annotations "eks.amazonaws.com/role-arn" }}
    web_identity_token_file = /var/run/secrets/eks.amazonaws.com/serviceaccount/token
{{- end }}
{{- end }}
