env: "circleci"
k8s_cluster_name: "minikube"
dns_host_domain: "localhost"
default_region: "us-west-2"
ml_account_id: "692474966980"
docker_repo_prefix: "692474966980.dkr.ecr.us-west-2.amazonaws.com"
redis_host: "redis-message-broker-master.default"
s3_bucket: "scale-ml-circleci"
profile_ml_worker: "default"
profile_ml_inference_worker: "default"
