apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "modelEngine.fullname" . }}-inference-framework-latest-config
  labels:
    product: common
    team: infra
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-2"
data:
  deepspeed: {{ .Values.inferenceFramework.deepspeed | default "latest" | quote }}
  text_generation_inference: {{ .Values.inferenceFramework.text_generation_inference | default "latest" | quote }}
  vllm: {{ .Values.inferenceFramework.vllm | default "latest" | quote }}
  vllm_batch: {{ .Values.inferenceFramework.vllm_batch | default "latest" | quote }}
  vllm_batch_v2: {{ .Values.inferenceFramework.vllm_batch_v2 | default "latest" | quote }}
  lightllm: {{ .Values.inferenceFramework.lightllm | default "latest" | quote }}
  tensorrt_llm: {{ .Values.inferenceFramework.tensorrt_llm | default "latest" | quote }}
