env: "circleci"
k8s_cluster_name: "minikube"
dns_host_domain: "localhost"
default_region: "us-west-2"
ml_account_id: "000000000000"
docker_repo_prefix: "public.ecr.aws/b2z8n5q1"
redis_host: "redis-message-broker-master.default"
s3_bucket: "test-bucket"
profile_ml_worker: "default"
profile_ml_inference_worker: "default"
