{{- if .Values.secrets.kubernetesDatabaseSecretName }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "llmEngine.fullname" . }}-spellbook-setup
  labels:
    {{- include "llmEngine.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 0
  activeDeadlineSeconds: 600
  template:
    metadata:
      labels:
        sidecar.istio.io/inject: "false"
        {{- include "llmEngine.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "llmEngine.fullname" . }}
          image: "{{ .Values.image.gatewayRepository }}:{{ .Values.tag}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - dumb-init
            - --
          args:
            - python
            - -m
            - llm_engine.entrypoints.init_spellbook_models
            - --gateway-url
            - 'http://{{- include "llmEngine.fullname" . }}.{{ .Release.Namespace }}:{{ .Values.service.port }}'
          {{- include "llmEngine.serviceEnv" . | indent 10 }}
          {{- include "llmEngine.volumeMounts" . | indent 10 }}
      serviceAccountName: {{ include "llmEngine.fullname" . }}
      {{- include "llmEngine.volumes" . | indent 6 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
